<Project Sdk="Godot.NET.Sdk/4.5.1" InitialTargets="CheckDependencyPaths">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>true</ImplicitUsings>
        <Nullable>enable</Nullable> <!--Makes code analysis regarding null values stricter.-->
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DefaultItemExcludes>packages/**</DefaultItemExcludes>
        <AppOutputBase>$(MSBuildProjectDirectory)\</AppOutputBase>
        <PathMap>$(AppOutputBase)=.\</PathMap>
    </PropertyGroup>

    <!-- OS Detection -->
    <PropertyGroup>
        <IsWindows>false</IsWindows>
        <IsLinux>false</IsLinux>
        <IsOSX>false</IsOSX>
        <IsWindows Condition="$([MSBuild]::IsOSPlatform('Windows'))">true</IsWindows>
        <IsLinux Condition="$([MSBuild]::IsOSPlatform('Linux'))">true</IsLinux>
        <IsOSX Condition="$([MSBuild]::IsOSPlatform('OSX'))">true</IsOSX>
    </PropertyGroup>
    
    <!-- Windows -->
    <PropertyGroup Condition="'$(IsWindows)' == 'true'">
        <AutoSteamPath>$(registry:HKEY_CURRENT_USER\Software\Valve\Steam@SteamPath)\steamapps</AutoSteamPath>
        <SteamLibraryPath Condition="Exists('$(AutoSteamPath)/common/Slay the Spire 2')">$(AutoSteamPath)</SteamLibraryPath>

        <!-- If on Windows and Slay the Spire 2 is not installed in your default steam library, adjust the following.-->
        <SteamLibraryPath Condition="'$(SteamLibraryPath)' == ''">C:/Program Files (x86)/Steam/steamapps</SteamLibraryPath>

        <!-- The below should not need to be changed. -->
        <Sts2Path>$(SteamLibraryPath)/common/Slay the Spire 2</Sts2Path>
        <ModsPath>$(Sts2Path)/mods/</ModsPath>
        <Sts2DataDir>$(Sts2Path)/data_sts2_windows_x86_64</Sts2DataDir>
    </PropertyGroup>

    <!-- Linux -->
    <PropertyGroup Condition="'$(IsLinux)' == 'true'">
        <SteamLibraryPath Condition="'$(SteamLibraryPath)' == ''">$(HOME)/.local/share/Steam/steamapps</SteamLibraryPath>
        
        <!-- The below should not need to be changed. -->
        <Sts2Path>$(SteamLibraryPath)/common/Slay the Spire 2</Sts2Path>
        <ModsPath>$(Sts2Path)/mods/</ModsPath>
        <Sts2DataDir>$(Sts2Path)/data_sts2_linuxbsd_x86_64</Sts2DataDir>
    </PropertyGroup>

    <!-- macOS -->
    <PropertyGroup Condition="'$(IsOSX)' == 'true'">
        <SteamLibraryPath Condition="'$(SteamLibraryPath)' == ''">$(HOME)/Library/Application Support/Steam/steamapps</SteamLibraryPath>

        <!-- The below should not need to be changed. -->
        <Sts2Path>$(SteamLibraryPath)/common/Slay the Spire 2</Sts2Path>
        <ModsPath>$(Sts2Path)/SlayTheSpire2.app/Contents/MacOS/mods/</ModsPath>
        <Sts2DataDir>$(Sts2Path)/SlayTheSpire2.app/Contents/Resources/data_sts2_macos_x86_64</Sts2DataDir>
    </PropertyGroup>

    <PropertyGroup>
        <!-- Diasble architecture mismatch warning; mods are ideally built for all platforms (MSIL)
             while your local StS2 version will be for your specific platform. -->
        <NoWarn>$(NoWarn);MSB3270</NoWarn>
    </PropertyGroup>

    <ItemGroup Condition="Exists('$(Sts2DataDir)')">
        <Reference Include="0Harmony">
            <HintPath>stripped_libs/0Harmony-stripped.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="sts2">
            <HintPath>stripped_libs/sts2-stripped.dll</HintPath>
            <Private>false</Private>
            <Publicize>True</Publicize> <!--Allows private/protected field references but may cause errors.-->
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Alchyr.Sts2.ModAnalyzers" Version="*"/>
        <AdditionalFiles Include="ShowCardDmgInRewards/localization/**/*.json"/>
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="ShowCardDmgInRewards/**"/>
        <Compile Remove="materials/**"/>
        <Compile Remove="shaders/**"/>
        <Compile Remove="images/**"/>
        <EmbeddedResource Remove="ShowCardDmgInRewards/**"/>
        <EmbeddedResource Remove="materials/**"/>
        <EmbeddedResource Remove="shaders/**"/>
        <EmbeddedResource Remove="images/**"/>
    </ItemGroup>

    <ItemGroup>
        <None Include=".gitignore"/>
        <None Include="ShowCardDmgInRewards.json"/>
        <None Include="CHANGELOG.md"/>
        <None Include="ShowCardDmgInRewards/**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <Target Name="CheckDependencyPaths">
        <Message
                Text=" Slay the Spire 2 data not found at path '$(Sts2DataDir)'"
                Condition="'$(Sts2DataDir)' == '' or !Exists('$(Sts2DataDir)')"/>
    </Target>
    
    <Target Name="UpdateJsonVersion" BeforeTargets="BeforeBuild">
        <Exec Command="git describe --abbrev=0" ConsoleToMSBuild="true">
            <Output TaskParameter="ConsoleOutput" PropertyName="GitTag" />
        </Exec>
        <Exec Command="dotnet tool install -g dotnet-json" />
        <Exec Command="dotnet json set ShowCardDmgInRewards.json version &quot;$(GitTag)&quot;" />
    </Target>

    <Target Name="CopyToModsFolderOnBuild" AfterTargets="PostBuildEvent" Condition="Exists('$(ModsPath)')">
        <Message Text="Copying .dll and manifest to mods folder." Importance="high"/>
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/"/>
        <Copy SourceFiles="ShowCardDmgInRewards.json" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/"/>
    </Target>

    <Target Name="CopyToOutputFolderOnBuild" AfterTargets="PostBuildEvent" Condition="!Exists('$(ModsPath)')">
        <Message Text="Copying .dll and manifest to mods folder." Importance="high"/>
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="bin/$(MSBuildProjectName)/"/>
        <Copy SourceFiles="ShowCardDmgInRewards.json" DestinationFolder="bin/$(MSBuildProjectName)/"/>
    </Target>

</Project>